/*
 Aitana Alvarez - 340201
 Valentina Ramos - 224347
 */
package interfaz;

import dominio.*;
import java.util.ArrayList;
import archivos.ManejadorArchivos;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import java.text.ParseException;
import java.awt.Color;
import java.awt.Component;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.DefaultListCellRenderer;
import javax.swing.JList;
import javax.swing.ListSelectionModel;

public class VentanaPaquetes extends javax.swing.JFrame implements Observer{
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPaquetes.class.getName());

    private Sistema sistema;
    private ArrayList<Paquete> paquetesPendientesEnvio;
    private ArrayList<Paquete> paquetesSeleccionadosEnvio;
    private ArrayList<Funcionario> funcionariosEnvio;
    private ArrayList<Envio> enviosRecepcion;
private ArrayList<Paquete> paquetesRecepcion;
    
    public VentanaPaquetes(Sistema unSistema) {
        initComponents();
        sistema = unSistema;
        sistema.agregarObserver(this);
        configurarFechaPaquete();
        cargarDatosIniciales();
        configurarEnvio();
        configurarFechaEnvio();
        configurarRecepcion();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPaquetes = new javax.swing.JTabbedPane();
        pnlIngreso = new javax.swing.JPanel();
        lblIngreso = new javax.swing.JLabel();
        lblIdent = new javax.swing.JLabel();
        lblCliente = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblDest = new javax.swing.JLabel();
        lblDir = new javax.swing.JLabel();
        lblDep = new javax.swing.JLabel();
        lblPeso = new javax.swing.JLabel();
        cboCliente = new javax.swing.JComboBox<>();
        cboDepartamento = new javax.swing.JComboBox<>();
        txtPesoGramos = new javax.swing.JTextField();
        txtIdentificador = new javax.swing.JTextField();
        txtDestinatario = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtFechaPaquete = new javax.swing.JFormattedTextField();
        lblTextoZona = new javax.swing.JLabel();
        lblTextoPrecio = new javax.swing.JLabel();
        btnCalcularPrecio = new javax.swing.JButton();
        btnConfirmarPaquete = new javax.swing.JButton();
        btnLimpiarPaquete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPaquetes = new javax.swing.JTable();
        lblPaqReg = new javax.swing.JLabel();
        lblZonaRes = new javax.swing.JLabel();
        lblPrecioRes = new javax.swing.JLabel();
        pnlEnvio = new javax.swing.JPanel();
        lblNumEnvio = new javax.swing.JLabel();
        lblFechaEnvio = new javax.swing.JLabel();
        lblFun = new javax.swing.JLabel();
        lblZonaEnvio = new javax.swing.JLabel();
        lblNumEnvioRes = new javax.swing.JLabel();
        cboFun = new javax.swing.JComboBox<>();
        cboZonaEnvio = new javax.swing.JComboBox<>();
        lblPend = new javax.swing.JLabel();
        lblSel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstSeleccionados = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstPendientes = new javax.swing.JList<>();
        btnAgregarAEnvio = new javax.swing.JButton();
        btnQuitarDeEnvio = new javax.swing.JButton();
        lblCnt = new javax.swing.JLabel();
        lblPesoTotal = new javax.swing.JLabel();
        lblMonto = new javax.swing.JLabel();
        lblCntPaqRes = new javax.swing.JLabel();
        lblPesoTotRes = new javax.swing.JLabel();
        lblMontTotRes = new javax.swing.JLabel();
        btnConfirmarEnvio = new javax.swing.JButton();
        btnLimpiarEnvio = new javax.swing.JButton();
        txtFechaEnvio = new javax.swing.JFormattedTextField();
        pnlRecepcion = new javax.swing.JPanel();
        lblEnviosRegistrados = new javax.swing.JLabel();
        lblPaquetesRecepcion = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstEnvios = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstPaquetesRecepcion = new javax.swing.JList<>();
        lblEstadoEnvio = new javax.swing.JLabel();
        lblEstadoEnvioRes = new javax.swing.JLabel();
        btnConfirmarRecepcion = new javax.swing.JButton();
        btnLimpiarRecepcion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Paquetes");
        setSize(new java.awt.Dimension(0, 0));

        pnlPaquetes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        pnlIngreso.setBackground(new java.awt.Color(250, 250, 250));

        lblIngreso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblIngreso.setText("Ingreso de Paquete");

        lblIdent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIdent.setText("Identificador:");

        lblCliente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCliente.setText("Cliente:");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblFecha.setText("Fecha:");

        lblDest.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDest.setText("Destinatario:");

        lblDir.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDir.setText("Dirección:");

        lblDep.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDep.setText("Departamento:");

        lblPeso.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPeso.setText("Peso en gramos:");

        cboCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboClienteActionPerformed(evt);
            }
        });

        cboDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtIdentificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdentificadorActionPerformed(evt);
            }
        });

        txtFechaPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaPaqueteActionPerformed(evt);
            }
        });

        lblTextoZona.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTextoZona.setText("Zona:");

        lblTextoPrecio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTextoPrecio.setText("Precio:");

        btnCalcularPrecio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnCalcularPrecio.setText("Calcular precio");
        btnCalcularPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularPrecioActionPerformed(evt);
            }
        });

        btnConfirmarPaquete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConfirmarPaquete.setText("Confirmar ingreso");
        btnConfirmarPaquete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarPaqueteActionPerformed(evt);
            }
        });

        btnLimpiarPaquete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiarPaquete.setText("Limpiar");

        tablaPaquetes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Identificador", "Cliente", "Fecha", "Destinatario", "Dirección", "Departamento", "Zona", "Peso (g)", "Precio", "Estado"
            }
        ));
        jScrollPane1.setViewportView(tablaPaquetes);

        lblPaqReg.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPaqReg.setText("Paquetes registrados:");

        lblZonaRes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblZonaRes.setText("-");

        lblPrecioRes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPrecioRes.setText("-");

        javax.swing.GroupLayout pnlIngresoLayout = new javax.swing.GroupLayout(pnlIngreso);
        pnlIngreso.setLayout(pnlIngresoLayout);
        pnlIngresoLayout.setHorizontalGroup(
            pnlIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlIngresoLayout.createSequentialGroup()
                        .addGroup(pnlIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlIngresoLayout.createSequentialGroup()
                                .addGroup(pnlIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDest)
                                    .addComponent(lblDir))
                                .addGap(43, 43, 43)
                                .addGroup(pnlIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlIngresoLayout.createSequentialGroup()
                                        .addGroup(pnlIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtPesoGramos, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboDepartamento, javax.swing.GroupLayout.Alignment.LEADING, 0, 155, Short.MAX_VALUE)
                                            .addComponent(txtDireccion, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnCalcularPrecio))
                                    .addComponent(txtFechaPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblDep)
                            .addComponent(lblIdent)
                            .addComponent(lblIngreso)
                            .addComponent(lblCliente)
                            .addComponent(lblFecha)
                            .addComponent(lblPeso)
                            .addGroup(pnlIngresoLayout.createSequentialGroup()
                                .addGroup(pnlIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblTextoPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                    .addComponent(lblTextoZona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(62, 62, 62)
                                .addGroup(pnlIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrecioRes, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnlIngresoLayout.createSequentialGroup()
                                        .addGap(336, 336, 336)
                                        .addComponent(btnLimpiarPaquete))
                                    .addComponent(lblZonaRes, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlIngresoLayout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(pnlIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnConfirmarPaquete)
                                    .addComponent(lblPaqReg, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 303, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlIngresoLayout.setVerticalGroup(
            pnlIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlIngresoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblIngreso)
                .addGap(11, 11, 11)
                .addGroup(pnlIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdent)
                    .addComponent(txtIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(pnlIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCliente)
                    .addComponent(cboCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFecha)
                    .addComponent(txtFechaPaquete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDest)
                    .addComponent(txtDestinatario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pnlIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDep)
                    .addComponent(cboDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(pnlIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPeso)
                    .addComponent(txtPesoGramos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCalcularPrecio))
                .addGap(10, 10, 10)
                .addGroup(pnlIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTextoZona)
                    .addComponent(lblZonaRes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPrecioRes, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblTextoPrecio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlIngresoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConfirmarPaquete)
                    .addComponent(btnLimpiarPaquete))
                .addGap(6, 6, 6)
                .addComponent(lblPaqReg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlPaquetes.addTab("Ingreso", pnlIngreso);

        lblNumEnvio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNumEnvio.setText("Nº de envío:");

        lblFechaEnvio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFechaEnvio.setText("Fecha:");

        lblFun.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFun.setText("Funcionario: ");

        lblZonaEnvio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblZonaEnvio.setText("Zona:");

        lblNumEnvioRes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNumEnvioRes.setText("-");

        cboFun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cboZonaEnvio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboZonaEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboZonaEnvioActionPerformed(evt);
            }
        });

        lblPend.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPend.setText("Paquetes pendientes:");

        lblSel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSel.setText("Paquetes seleccionados:");

        lstSeleccionados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(lstSeleccionados);

        lstPendientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(lstPendientes);

        btnAgregarAEnvio.setText(">>");
        btnAgregarAEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAEnvioActionPerformed(evt);
            }
        });

        btnQuitarDeEnvio.setText("<<");
        btnQuitarDeEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarDeEnvioActionPerformed(evt);
            }
        });

        lblCnt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblCnt.setText("Cantidad de paquetes:");

        lblPesoTotal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPesoTotal.setText("Peso total:");

        lblMonto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMonto.setText("Monto total:");

        lblCntPaqRes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCntPaqRes.setText("-");

        lblPesoTotRes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblPesoTotRes.setText("-");

        lblMontTotRes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblMontTotRes.setText("-");

        btnConfirmarEnvio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConfirmarEnvio.setText("Confirmar envío");
        btnConfirmarEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarEnvioActionPerformed(evt);
            }
        });

        btnLimpiarEnvio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiarEnvio.setText("Limpiar");
        btnLimpiarEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarEnvioActionPerformed(evt);
            }
        });

        txtFechaEnvio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaEnvioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEnvioLayout = new javax.swing.GroupLayout(pnlEnvio);
        pnlEnvio.setLayout(pnlEnvioLayout);
        pnlEnvioLayout.setHorizontalGroup(
            pnlEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnvioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCnt)
                    .addComponent(lblMonto)
                    .addComponent(lblPesoTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnlEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEnvioLayout.createSequentialGroup()
                        .addComponent(lblCntPaqRes, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlEnvioLayout.createSequentialGroup()
                        .addGroup(pnlEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblMontTotRes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPesoTotRes, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                        .addGap(528, 528, 528))))
            .addGroup(pnlEnvioLayout.createSequentialGroup()
                .addGroup(pnlEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEnvioLayout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(lblPend))
                    .addGroup(pnlEnvioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlEnvioLayout.createSequentialGroup()
                                .addGap(164, 164, 164)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addGroup(pnlEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAgregarAEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnQuitarDeEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnlEnvioLayout.createSequentialGroup()
                                .addGroup(pnlEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblFun)
                                    .addComponent(lblZonaEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cboFun, 0, 150, Short.MAX_VALUE)
                                    .addComponent(cboZonaEnvio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtFechaEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(72, 72, 72)
                .addGroup(pnlEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEnvioLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblSel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEnvioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEnvioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnLimpiarEnvio)
                        .addGap(101, 101, 101))
                    .addGroup(pnlEnvioLayout.createSequentialGroup()
                        .addGroup(pnlEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumEnvio)
                            .addComponent(lblFechaEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNumEnvioRes, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pnlEnvioLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(btnConfirmarEnvio)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlEnvioLayout.setVerticalGroup(
            pnlEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEnvioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnlEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumEnvio)
                    .addComponent(lblNumEnvioRes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaEnvio)
                    .addComponent(txtFechaEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pnlEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFun)
                    .addComponent(cboFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblZonaEnvio)
                    .addComponent(cboZonaEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEnvioLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btnAgregarAEnvio)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnQuitarDeEnvio))
                    .addGroup(pnlEnvioLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPend)
                            .addComponent(lblSel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(pnlEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCnt)
                    .addComponent(lblCntPaqRes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPesoTotal)
                    .addComponent(lblPesoTotRes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(pnlEnvioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMonto)
                    .addComponent(lblMontTotRes))
                .addGap(18, 18, 18)
                .addComponent(btnConfirmarEnvio)
                .addGap(15, 15, 15)
                .addComponent(btnLimpiarEnvio)
                .addGap(28, 28, 28))
        );

        pnlPaquetes.addTab("Envío", pnlEnvio);

        lblEnviosRegistrados.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEnviosRegistrados.setText("Envíos registrados");

        lblPaquetesRecepcion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblPaquetesRecepcion.setText("Paquetes del envío");

        lstEnvios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(lstEnvios);

        lstPaquetesRecepcion.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(lstPaquetesRecepcion);

        lblEstadoEnvio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblEstadoEnvio.setText("Estado del envío:");

        lblEstadoEnvioRes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblEstadoEnvioRes.setText("-");

        btnConfirmarRecepcion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnConfirmarRecepcion.setText("Confirmar recepción");

        btnLimpiarRecepcion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLimpiarRecepcion.setText("Limpiar");

        javax.swing.GroupLayout pnlRecepcionLayout = new javax.swing.GroupLayout(pnlRecepcion);
        pnlRecepcion.setLayout(pnlRecepcionLayout);
        pnlRecepcionLayout.setHorizontalGroup(
            pnlRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecepcionLayout.createSequentialGroup()
                .addGroup(pnlRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlRecepcionLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(lblEstadoEnvio, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblEstadoEnvioRes, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlRecepcionLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(pnlRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEnviosRegistrados)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(144, 144, 144)
                        .addGroup(pnlRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPaquetesRecepcion)))
                    .addGroup(pnlRecepcionLayout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(btnConfirmarRecepcion))
                    .addGroup(pnlRecepcionLayout.createSequentialGroup()
                        .addGap(357, 357, 357)
                        .addComponent(btnLimpiarRecepcion)))
                .addContainerGap(272, Short.MAX_VALUE))
        );
        pnlRecepcionLayout.setVerticalGroup(
            pnlRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRecepcionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEnviosRegistrados)
                    .addComponent(lblPaquetesRecepcion))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(76, 76, 76)
                .addGroup(pnlRecepcionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstadoEnvio)
                    .addComponent(lblEstadoEnvioRes))
                .addGap(18, 18, 18)
                .addComponent(btnConfirmarRecepcion)
                .addGap(34, 34, 34)
                .addComponent(btnLimpiarRecepcion)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        pnlPaquetes.addTab("Recepción", pnlRecepcion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlPaquetes)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlPaquetes)
                .addContainerGap())
        );

        pnlPaquetes.getAccessibleContext().setAccessibleName("Paquetes");

        pack();
    }// </editor-fold>//GEN-END:initComponents
// =====================================================================
    // LISTA DE DEPARTAMENTOS FIJA (19 departamentos del país)
    // =====================================================================
    private static final String[] DEPARTAMENTOS = {
        "Artigas", "Salto", "Paysandú", "Rivera", "Tacuarembó",
        "Río Negro", "Soriano", "Colonia", "San José",
        "Cerro Largo", "Treinta y Tres", "Lavalleja", "Rocha", "Maldonado",
        "Durazno", "Flores", "Florida", "Canelones", "Montevideo"
    };

    // =====================================================================
    // CARGA INICIAL
    // =====================================================================
   private void cargarDatosIniciales() {
        cargarComboClientes();
        cargarComboDepartamentos();
        cargarTablaPaquetes();
    }

    private void cargarComboClientes() {
        cboCliente.removeAllItems();

        for (int i = 0; i < sistema.getListaClientes().size(); i = i + 1) {
            Cliente cliente = sistema.getListaClientes().get(i);
            cboCliente.addItem(cliente.getNombre());
        }
    }

    private void cargarComboDepartamentos() {
        cboDepartamento.removeAllItems();

        for (int i = 0; i < DEPARTAMENTOS.length; i = i + 1) {
            cboDepartamento.addItem(DEPARTAMENTOS[i]);
        }
    }

    private void cargarTablaPaquetes() {
        DefaultTableModel modelo = new DefaultTableModel(
                new String[]{"Identificador", "Cliente", "Fecha", "Destinatario",
                    "Dirección", "Departamento", "Zona", "Peso (g)", "Precio", "Estado"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        for (int i = 0; i < sistema.getListaPaquetes().size(); i = i + 1) {
            Paquete paquete = sistema.getListaPaquetes().get(i);

            modelo.addRow(new Object[]{
                paquete.getIdentificador(),
                paquete.getCliente().getNombre(),
                paquete.getFecha(),
                paquete.getDestinatario(),
                paquete.getDireccion(),
                paquete.getDepartamento(),
                paquete.getZona(),
                paquete.getPesoGramos(),
                "$" + paquete.getPrecio(),
                paquete.getEstado()
            });
        }

        tablaPaquetes.setModel(modelo);
    }

    private void configurarFechaPaquete() {
        try {
            MaskFormatter mascaraFecha = new MaskFormatter("##/##/####");
            mascaraFecha.setPlaceholderCharacter('_');
            txtFechaPaquete.setFormatterFactory(
                    new javax.swing.text.DefaultFormatterFactory(mascaraFecha)
            );
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Error al configurar la fecha.");
        }
    }

    // =====================================================================
    // INGRESO DE PAQUETES
    // =====================================================================
    private void calcularPrecio() {
        String textoPeso = txtPesoGramos.getText().trim();

        lblZonaRes.setText("-");
        lblPrecioRes.setText("-");

        if (textoPeso.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar el peso en gramos.");
            return;
        }

        try {
            int pesoGramos = Integer.parseInt(textoPeso);

            if (pesoGramos <= 0) {
                JOptionPane.showMessageDialog(this, "El peso debe ser mayor a cero.");
                return;
            }

            String departamento = (String) cboDepartamento.getSelectedItem();

            if (departamento == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un departamento.");
                return;
            }

            String zona = sistema.darZonaDepartamento(departamento);
            int precio = sistema.calcularPrecio(zona, pesoGramos);

            lblZonaRes.setText(zona);
            lblPrecioRes.setText("$" + precio);

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El peso debe ser un número entero en gramos.");
        }
    }

    private Cliente obtenerClienteSeleccionado() {
        Cliente clienteEncontrado = null;
        String nombreCliente = (String) cboCliente.getSelectedItem();

        for (int i = 0; i < sistema.getListaClientes().size(); i = i + 1) {
            Cliente cliente = sistema.getListaClientes().get(i);

            if (cliente.getNombre().equals(nombreCliente)) {
                clienteEncontrado = cliente;
            }
        }

        return clienteEncontrado;
    }

    private void confirmarPaquete() {
        String identificador = txtIdentificador.getText().trim();
        String fecha = txtFechaPaquete.getText().trim();
        String destinatario = txtDestinatario.getText().trim();
        String direccion = txtDireccion.getText().trim();
        String textoPeso = txtPesoGramos.getText().trim();

        if (identificador.isEmpty() || fecha.isEmpty() || destinatario.isEmpty()
                || direccion.isEmpty() || textoPeso.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe completar todos los campos.");
            return;
        }

        if (cboCliente.getSelectedIndex() < 0) {
            JOptionPane.showMessageDialog(this, "No hay clientes registrados. Registre un cliente primero.");
            return;
        }

        if (sistema.existePaquete(identificador)) {
            JOptionPane.showMessageDialog(this, "Ya existe un paquete con ese identificador.");
            return;
        }

        int pesoGramos;
        try {
            pesoGramos = Integer.parseInt(textoPeso);

            if (pesoGramos <= 0) {
                JOptionPane.showMessageDialog(this, "El peso debe ser mayor a cero.");
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "El peso debe ser un número entero en gramos.");
            return;
        }

        Cliente clienteSeleccionado = obtenerClienteSeleccionado();

        if (clienteSeleccionado == null) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un cliente.");
            return;
        }

        String departamento = (String) cboDepartamento.getSelectedItem();
        String zona = sistema.darZonaDepartamento(departamento);
        int precio = sistema.calcularPrecio(zona, pesoGramos);

        int opcion = JOptionPane.showConfirmDialog(this,
                "Zona: " + zona + "\nPrecio a cobrar: $" + precio + "\n\n¿Confirmar ingreso del paquete?",
                "Confirmar paquete",
                JOptionPane.YES_NO_OPTION);

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        Paquete paquete = new Paquete(identificador, clienteSeleccionado, fecha,
                destinatario, direccion, departamento, zona, pesoGramos, precio);

        sistema.agregarPaquete(paquete);
        ManejadorArchivos.registrarTransaccion("Ingreso de paquete " + identificador
                + " de cliente " + clienteSeleccionado.getNombre());

        cargarTablaPaquetes();
        cargarPendientesEnvio();
        limpiarFormulario();

        JOptionPane.showMessageDialog(this, "Paquete ingresado correctamente.");
    }

    private void limpiarFormulario() {
        txtIdentificador.setText("");
        txtFechaPaquete.setText("");
        txtDestinatario.setText("");
        txtDireccion.setText("");
        txtPesoGramos.setText("");
        lblZonaRes.setText("-");
        lblPrecioRes.setText("-");

        if (cboCliente.getItemCount() > 0) {
            cboCliente.setSelectedIndex(0);
        }

        if (cboDepartamento.getItemCount() > 0) {
            cboDepartamento.setSelectedIndex(0);
        }
    }

    // =====================================================================
    // ENVÍO DE PAQUETES
    // =====================================================================
    private void configurarEnvio() {
        paquetesPendientesEnvio = new ArrayList<Paquete>();
        paquetesSeleccionadosEnvio = new ArrayList<Paquete>();
        funcionariosEnvio = new ArrayList<Funcionario>();

        cargarFuncionariosEnvio();
        cargarZonasEnvio();
        limpiarEnvio();
    }

    private void cargarFuncionariosEnvio() {
        cboFun.removeAllItems();
        funcionariosEnvio.clear();

        for (int i = 0; i < sistema.getListaFuncionarios().size(); i = i + 1) {
            Funcionario funcionario = sistema.getListaFuncionarios().get(i);
            funcionariosEnvio.add(funcionario);
            cboFun.addItem(funcionario.toString());
        }
    }

    private void cargarZonasEnvio() {
        cboZonaEnvio.removeAllItems();
        cboZonaEnvio.addItem("NORTE");
        cboZonaEnvio.addItem("OESTE");
        cboZonaEnvio.addItem("ESTE");
        cboZonaEnvio.addItem("SUR");
    }

    private void cargarPendientesEnvio() {
        paquetesPendientesEnvio.clear();
        String zonaSeleccionada = (String) cboZonaEnvio.getSelectedItem();

        if (zonaSeleccionada != null) {
            for (int i = 0; i < sistema.getListaPaquetes().size(); i = i + 1) {
                Paquete paquete = sistema.getListaPaquetes().get(i);

                if (paquete.getEstado().trim().equalsIgnoreCase("pendiente")
                        && paquete.getZona().trim().equalsIgnoreCase(zonaSeleccionada.trim())) {
                    paquetesPendientesEnvio.add(paquete);
                }
            }
        }

        actualizarListasEnvio();
    }

    private void actualizarListasEnvio() {
        String[] datosPendientes = new String[paquetesPendientesEnvio.size()];

        for (int i = 0; i < paquetesPendientesEnvio.size(); i = i + 1) {
            Paquete paquete = paquetesPendientesEnvio.get(i);
            datosPendientes[i] = textoPaqueteEnvio(paquete);
        }

        lstPendientes.setListData(datosPendientes);

        String[] datosSeleccionados = new String[paquetesSeleccionadosEnvio.size()];

        for (int i = 0; i < paquetesSeleccionadosEnvio.size(); i = i + 1) {
            Paquete paquete = paquetesSeleccionadosEnvio.get(i);
            datosSeleccionados[i] = textoPaqueteEnvio(paquete);
        }

        lstSeleccionados.setListData(datosSeleccionados);

        actualizarResumenEnvio();
    }

    private String textoPaqueteEnvio(Paquete paquete) {
        return paquete.getIdentificador()
                + " - " + paquete.getCliente().getNombre()
                + " - " + paquete.getPesoGramos() + " g"
                + " - $" + paquete.getPrecio();
    }

    private void agregarPaqueteAEnvio() {
        int posicion = lstPendientes.getSelectedIndex();

        if (posicion < 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un paquete pendiente.");
        } else {
            Paquete paquete = paquetesPendientesEnvio.get(posicion);
            paquetesSeleccionadosEnvio.add(paquete);
            paquetesPendientesEnvio.remove(posicion);
            actualizarListasEnvio();
        }
    }

    private void quitarPaqueteDeEnvio() {
        int posicion = lstSeleccionados.getSelectedIndex();

        if (posicion < 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un paquete de la lista de seleccionados.");
        } else {
            Paquete paquete = paquetesSeleccionadosEnvio.get(posicion);
            paquetesPendientesEnvio.add(paquete);
            paquetesSeleccionadosEnvio.remove(posicion);
            actualizarListasEnvio();
        }
    }

    private void actualizarResumenEnvio() {
        int cantidad = 0;
        int pesoTotal = 0;
        int montoTotal = 0;

        if (paquetesSeleccionadosEnvio != null) {
            cantidad = paquetesSeleccionadosEnvio.size();

            for (int i = 0; i < paquetesSeleccionadosEnvio.size(); i = i + 1) {
                Paquete paquete = paquetesSeleccionadosEnvio.get(i);
                pesoTotal = pesoTotal + paquete.getPesoGramos();
                montoTotal = montoTotal + paquete.getPrecio();
            }
        }

        lblCntPaqRes.setText("" + cantidad);
        lblPesoTotRes.setText(formatearPeso(pesoTotal));
        lblMontTotRes.setText("$" + montoTotal);
    }

    private String formatearPeso(int pesoGramos) {
        int kilos = pesoGramos / 1000;
        int gramos = pesoGramos % 1000;
        return kilos + " kg, " + gramos + " gramos";
    }

    private Funcionario obtenerFuncionarioEnvioSeleccionado() {
        Funcionario funcionario = null;
        int posicion = cboFun.getSelectedIndex();

        if (posicion >= 0 && posicion < funcionariosEnvio.size()) {
            funcionario = funcionariosEnvio.get(posicion);
        }

        return funcionario;
    }

    private void confirmarEnvio() {
        String fecha = txtFechaEnvio.getText().trim();
        Funcionario funcionario = obtenerFuncionarioEnvioSeleccionado();
        String zona = (String) cboZonaEnvio.getSelectedItem();

        if (fecha.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Debe ingresar la fecha del envío.");
        } else {
            if (funcionario == null) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un funcionario.");
            } else {
                if (paquetesSeleccionadosEnvio.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "Debe seleccionar al menos un paquete.");
                } else {
                    ArrayList<Paquete> copiaSeleccionados = new ArrayList<Paquete>();

                    for (int i = 0; i < paquetesSeleccionadosEnvio.size(); i = i + 1) {
                        copiaSeleccionados.add(paquetesSeleccionadosEnvio.get(i));
                    }

                    Envio envio = sistema.crearEnvio(fecha, funcionario, zona, copiaSeleccionados);
                    ManejadorArchivos.registrarTransaccion("Ingreso de envío número " + envio.getNumero());

                    JOptionPane.showMessageDialog(this, "Envío registrado correctamente.");

                    cargarTablaPaquetes();
                    limpiarEnvio();
                }
            }
        }
    }

    private void limpiarEnvio() {
        txtFechaEnvio.setText("");
        lblNumEnvioRes.setText("" + sistema.getProximoNumeroEnvio());

        if (cboFun.getItemCount() > 0) {
            cboFun.setSelectedIndex(0);
        }
        if (cboZonaEnvio.getItemCount() > 0) {
            cboZonaEnvio.setSelectedIndex(0);
        }

        paquetesSeleccionadosEnvio.clear();
        cargarPendientesEnvio();
        actualizarResumenEnvio();
    }

    private void cambiarZonaEnvio() {
        paquetesSeleccionadosEnvio.clear();
        cargarPendientesEnvio();
    }
    
    private void configurarFechaEnvio() {
        try {
            MaskFormatter mascaraFecha = new MaskFormatter("##/##/####");
            mascaraFecha.setPlaceholderCharacter('_');

            txtFechaEnvio.setFormatterFactory(
                new javax.swing.text.DefaultFormatterFactory(mascaraFecha)
            );

        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Error al configurar la fecha del envío.");
        }
}
    // =====================================================================
    // RECEPCIÓN DE ENVÍOS
    // =====================================================================
    private void configurarRecepcion() {
        enviosRecepcion = new ArrayList<Envio>();
        paquetesRecepcion = new ArrayList<Paquete>();

        lstPaquetesRecepcion.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        lstEnvios.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList<?> lista, Object valor,
                    int indice, boolean seleccionado, boolean tieneFoco) {

                Component componente = super.getListCellRendererComponent(
                        lista, valor, indice, seleccionado, tieneFoco);

                if (indice >= 0 && indice < enviosRecepcion.size()) {
                    Envio envio = enviosRecepcion.get(indice);

                    if (envio.getRecibido()) {
                        componente.setBackground(Color.GREEN);
                    } else {
                        componente.setBackground(Color.YELLOW);
                    }

                    componente.setForeground(Color.BLACK);
                }

                return componente;
            }
        });

        lstEnvios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                if (!evt.getValueIsAdjusting()) {
                    seleccionarEnvioRecepcion();
                }
            }
        });

        btnConfirmarRecepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarRecepcion();
            }
        });

        btnLimpiarRecepcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarRecepcion();
            }
        });

        cargarEnviosRecepcion();
    }

    private void cargarEnviosRecepcion() {
        enviosRecepcion.clear();

        for (int i = 0; i < sistema.getListaEnvios().size(); i = i + 1) {
            enviosRecepcion.add(sistema.getListaEnvios().get(i));
        }

        Collections.sort(enviosRecepcion, new Comparator<Envio>() {
            public int compare(Envio envio1, Envio envio2) {
                return envio2.getNumero() - envio1.getNumero();
            }
        });

        String[] datos = new String[enviosRecepcion.size()];

        for (int i = 0; i < enviosRecepcion.size(); i = i + 1) {
            Envio envio = enviosRecepcion.get(i);
            datos[i] = textoEnvioRecepcion(envio);
        }

        lstEnvios.setListData(datos);
        limpiarRecepcion();
    }

    private String textoEnvioRecepcion(Envio envio) {
        return "Envío " + envio.getNumero()
                + " - " + envio.getFecha()
                + " - " + envio.getZona()
                + " - " + envio.getFuncionario();
    }

    private void seleccionarEnvioRecepcion() {
        int posicion = lstEnvios.getSelectedIndex();

        paquetesRecepcion.clear();

        if (posicion < 0) {
            lblEstadoEnvioRes.setText("-");
            lstPaquetesRecepcion.setListData(new String[0]);
            btnConfirmarRecepcion.setEnabled(false);
        } else {
            Envio envio = enviosRecepcion.get(posicion);

            if (envio.getRecibido()) {
                lblEstadoEnvioRes.setText("Recibido");
                btnConfirmarRecepcion.setEnabled(false);

                for (int i = 0; i < envio.getListaPaquetesEntregados().size(); i = i + 1) {
                    paquetesRecepcion.add(envio.getListaPaquetesEntregados().get(i));
                }
            } else {
                lblEstadoEnvioRes.setText("Pendiente de recepción");
                btnConfirmarRecepcion.setEnabled(true);

                for (int i = 0; i < envio.getListaPaquetes().size(); i = i + 1) {
                    paquetesRecepcion.add(envio.getListaPaquetes().get(i));
                }
            }

            cargarListaPaquetesRecepcion();
        }
    }

    private void cargarListaPaquetesRecepcion() {
        String[] datos = new String[paquetesRecepcion.size()];

        for (int i = 0; i < paquetesRecepcion.size(); i = i + 1) {
            Paquete paquete = paquetesRecepcion.get(i);

            datos[i] = paquete.getIdentificador()
                    + " - " + paquete.getCliente().getNombre()
                    + " - " + paquete.getDepartamento()
                    + " - " + paquete.getPesoGramos() + " g"
                    + " - $" + paquete.getPrecio()
                    + " - " + paquete.getEstado();
        }

        lstPaquetesRecepcion.setListData(datos);
    }

    private void confirmarRecepcion() {
        int posicionEnvio = lstEnvios.getSelectedIndex();

        if (posicionEnvio < 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un envío.");
        } else {
            Envio envio = enviosRecepcion.get(posicionEnvio);

            if (envio.getRecibido()) {
                JOptionPane.showMessageDialog(this, "Ese envío ya tiene recepción registrada.");
            } else {
                int[] posiciones = lstPaquetesRecepcion.getSelectedIndices();

                ArrayList<Paquete> paquetesEntregados = new ArrayList<Paquete>();

                for (int i = 0; i < posiciones.length; i = i + 1) {
                    paquetesEntregados.add(paquetesRecepcion.get(posiciones[i]));
                }

                int opcion = JOptionPane.showConfirmDialog(this,
                        "Se marcarán como recibidos " + paquetesEntregados.size()
                        + " paquete(s).\nLos demás volverán a pendiente.\n\n¿Confirmar recepción?",
                        "Confirmar recepción",
                        JOptionPane.YES_NO_OPTION);

                if (opcion == JOptionPane.YES_OPTION) {
                    sistema.registrarRecepcion(envio, paquetesEntregados);

                    ManejadorArchivos.registrarTransaccion(
                            "Recepción de envío número " + envio.getNumero());

                    cargarTablaPaquetes();
                    cargarPendientesEnvio();
                    cargarEnviosRecepcion();

                    JOptionPane.showMessageDialog(this, "Recepción registrada correctamente.");
                }
            }
        }
    }

    private void limpiarRecepcion() {
        lstEnvios.clearSelection();
        paquetesRecepcion.clear();
        lstPaquetesRecepcion.setListData(new String[0]);
        lblEstadoEnvioRes.setText("-");
        btnConfirmarRecepcion.setEnabled(false);
    }
    private void txtIdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdentificadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdentificadorActionPerformed

    private void txtFechaPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaPaqueteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaPaqueteActionPerformed

    private void cboClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboClienteActionPerformed

    private void btnCalcularPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularPrecioActionPerformed
        calcularPrecio();
    }//GEN-LAST:event_btnCalcularPrecioActionPerformed

    private void btnConfirmarPaqueteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarPaqueteActionPerformed
        confirmarPaquete();
    }//GEN-LAST:event_btnConfirmarPaqueteActionPerformed

    private void btnAgregarAEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAEnvioActionPerformed
        agregarPaqueteAEnvio();
    }//GEN-LAST:event_btnAgregarAEnvioActionPerformed

    private void btnQuitarDeEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarDeEnvioActionPerformed
        quitarPaqueteDeEnvio();
    }//GEN-LAST:event_btnQuitarDeEnvioActionPerformed

    private void btnConfirmarEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarEnvioActionPerformed
        confirmarEnvio();
    }//GEN-LAST:event_btnConfirmarEnvioActionPerformed

    private void btnLimpiarEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarEnvioActionPerformed
        limpiarEnvio();
    }//GEN-LAST:event_btnLimpiarEnvioActionPerformed

    private void cboZonaEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboZonaEnvioActionPerformed
        cambiarZonaEnvio();
    }//GEN-LAST:event_cboZonaEnvioActionPerformed

    private void txtFechaEnvioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaEnvioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaEnvioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAEnvio;
    private javax.swing.JButton btnCalcularPrecio;
    private javax.swing.JButton btnConfirmarEnvio;
    private javax.swing.JButton btnConfirmarPaquete;
    private javax.swing.JButton btnConfirmarRecepcion;
    private javax.swing.JButton btnLimpiarEnvio;
    private javax.swing.JButton btnLimpiarPaquete;
    private javax.swing.JButton btnLimpiarRecepcion;
    private javax.swing.JButton btnQuitarDeEnvio;
    private javax.swing.JComboBox<String> cboCliente;
    private javax.swing.JComboBox<String> cboDepartamento;
    private javax.swing.JComboBox<String> cboFun;
    private javax.swing.JComboBox<String> cboZonaEnvio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCnt;
    private javax.swing.JLabel lblCntPaqRes;
    private javax.swing.JLabel lblDep;
    private javax.swing.JLabel lblDest;
    private javax.swing.JLabel lblDir;
    private javax.swing.JLabel lblEnviosRegistrados;
    private javax.swing.JLabel lblEstadoEnvio;
    private javax.swing.JLabel lblEstadoEnvioRes;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaEnvio;
    private javax.swing.JLabel lblFun;
    private javax.swing.JLabel lblIdent;
    private javax.swing.JLabel lblIngreso;
    private javax.swing.JLabel lblMontTotRes;
    private javax.swing.JLabel lblMonto;
    private javax.swing.JLabel lblNumEnvio;
    private javax.swing.JLabel lblNumEnvioRes;
    private javax.swing.JLabel lblPaqReg;
    private javax.swing.JLabel lblPaquetesRecepcion;
    private javax.swing.JLabel lblPend;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblPesoTotRes;
    private javax.swing.JLabel lblPesoTotal;
    private javax.swing.JLabel lblPrecioRes;
    private javax.swing.JLabel lblSel;
    private javax.swing.JLabel lblTextoPrecio;
    private javax.swing.JLabel lblTextoZona;
    private javax.swing.JLabel lblZonaEnvio;
    private javax.swing.JLabel lblZonaRes;
    private javax.swing.JList<String> lstEnvios;
    private javax.swing.JList<String> lstPaquetesRecepcion;
    private javax.swing.JList<String> lstPendientes;
    private javax.swing.JList<String> lstSeleccionados;
    private javax.swing.JPanel pnlEnvio;
    private javax.swing.JPanel pnlIngreso;
    private javax.swing.JTabbedPane pnlPaquetes;
    private javax.swing.JPanel pnlRecepcion;
    private javax.swing.JTable tablaPaquetes;
    private javax.swing.JTextField txtDestinatario;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JFormattedTextField txtFechaEnvio;
    private javax.swing.JFormattedTextField txtFechaPaquete;
    private javax.swing.JTextField txtIdentificador;
    private javax.swing.JTextField txtPesoGramos;
    // End of variables declaration//GEN-END:variables
    @Override
    public void actualizar() {
        cargarComboClientes();
        cargarFuncionariosEnvio();
        cargarTablaPaquetes();
        cargarPendientesEnvio();
        cargarEnviosRecepcion();
        lblNumEnvioRes.setText("" + sistema.getProximoNumeroEnvio());
    }
}
